# Generated by Django 3.1 on 2020-09-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_max_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='max_bid',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0, max_digits=12), max_digits=12),
        ),
    ]
