# Generated by Django 3.1 on 2020-09-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200923_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='max_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
